spark.app.name                    Spark Trustworthiness Estimator

spark.master                      k8s://https://k8s.srv.webis.de
spark.kubernetes.container.image  registry.webis.de/code-lib/public-images/webis/spark
spark.kubernetes.namespace        spark-jobs

# Required for cluster mode
spark.kubernetes.authenticate.driver.serviceAccountName spark

# Required for client mode (optionally with fixed ports)
spark.driver.host YOUR-HOSTNAME-OR-IP
#spark.driver.port              2222
#spark.driver.blockManager.port 2223

# Recommended, but not required (see "Scheduling")
spark.kubernetes.driver.annotation.yunikorn.apache.org/allow-preemption "false"

# Name of the pull secret for images from the Webis registry (already deployed)
spark.kubernetes.container.image.pullSecrets webis-registry-credentials